<?php

/*
 * @author Akbarali
 * Date: 31.12.2021
 * @telegram @kbarli
 * @website http://akbarali.uz
 * Email: Akbarali@uzhackersw.uz
 * Johncms Профил: https://johncms.com/profile/?user=38217
 * На тему: https://johncms.com/forum/?type=topic&id=12200
 */
$this->layout('system::layout/default') ?>
<div>Загрузить фотографии:</div>
<!-- File upload form -->
<form id="uploadForm" enctype="multipart/form-data">
    <div class="form-group">
        <div class="custom-file">
            <input type="file" name="image[]" id="fileInput" class="custom-file-input" accept="image/*,audio/mp3,audio/*" multiple="multiple" required>
            <label for="file" class="custom-file-label">Выберите файл</label>
        </div>
        <hr>
        <div class="progress">
            <div class="progress-bar progress-bar-striped" style="width: 0%;  animation: progress-bar-stripes 2s linear infinite;">
            </div>
        </div>
        <div id="uploadStatus"></div>
        <hr>
        <div class="text-muted mb-3 small">
            Разрешенные форматы изображений: JPG, GIF или PNG. Размер файла не должен превышать 1000 Кб.<br>The новое изображение заменит старое (если было).
        </div>
    </div>
    <div class="mt-3">
        <input type="submit" name="submit" value="Сохранить" class="btn btn-primary">
    </div>
</form>
<hr>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-3" id="boshi">
    <?php foreach ($images['data'] as $image): ?>
        <div class="col mb-4" id="image_<?= $image['id'] ?>">
            <div class="card py-0 h-100 overflow-hidden">
                <?php if ($image['type'] == 'audio'): ?>
                    <audio class="album-photo" controls src="<?= $image['file_path'] ?>">
                        Your browser does not support the audio element.
                    </audio>
                <?php else: ?>
                    <div class="album-photo" style="background: url('<?= $image['file_path'] ?>');"></div>
                <?php endif; ?>
                <div class="card-body d-flex px-3 flex-column justify-content-between" style=" padding: 10px; ">
                    <div class="small">
                      <span class="text-nowrap pr-2">
                      Добавлено: <a href="<?= $image['user']['profile_url'] ?>"><?= $image['user']['name'] ?></a><br>
                      </span>
                        <?php if ($user_rights >= 5): ?>
                            <span class="text-nowrap">
                                Действия: <a id="dellete" data-value="<?= $image['id'] ?>" style="cursor: pointer; text-decoration: line-through;">удалять</a>
                            </span>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="card-footer d-flex justify-content-between" style=" padding-bottom: 0px; ">
                    <div class="input-group mb-3">
                        <?php if ($image['type'] == 'audio'): ?>
                            <input type="text" value="[audio]<?= $image['name'] ?>[/audio]" id="photo<?= $image['id'] ?>" class="form-control">
                        <?php else: ?>
                            <input type="text" value="[img]<?= $image['name'] ?>[/img]" id="photo<?= $image['id'] ?>" class="form-control">
                        <?php endif; ?>
                        <button onclick="copybbcode('photo<?= $image['id'] ?>')" class="btn btn-primary" class="btn btn-outline-secondary">Copy</button>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<hr>
<?= $pagination ?>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Progress bar -->
<script>
    $(document).on("click", "#dellete", function () {
        var a = $(this).data("value"),
            b = confirm("Do you want to permanently delete this image?");
        if (true == b)
            $.ajax({
                url: '/image/delete/',
                type: "POST",
                data: {id: a},
                dataType: "json",
                success: function (resp) {
                    if (resp.success) {
                        $("#image_" + a).remove();
                    } else if (resp.error) {
                        alert(resp.message);
                    }
                }
            });
    });

    function copybbcode(bbcode) {
        var copyText = document.getElementById(bbcode);
        copyText.select();
        copyText.setSelectionRange(0, 99999)
        document.execCommand("copy");
    }

    $(document).ready(function () {
        // File upload via Ajax
        $("#uploadForm").on('submit', function (e) {
            e.preventDefault();
            $.ajax({
                xhr: function () {
                    var xhr = new window.XMLHttpRequest();
                    xhr.upload.addEventListener("progress", function (evt) {
                        if (evt.lengthComputable) {
                            var percentComplete = ((evt.loaded / evt.total) * 100);
                            $(".progress-bar").width(percentComplete + '%');
                            $(".progress-akb").val(percentComplete);
                            $(".progress-bar").html(percentComplete + '%');
                        }
                    }, false);
                    return xhr;
                },
                type: 'POST',
                url: '/image/upload',
                data: new FormData(this),
                processData: false,
                contentType: false,
                cache: false,
                beforeSend: function () {
                    $(".progress-bar").width('0%');
                    $(".progress-akb").val('0');
                    $('#uploadStatus').html('<p style="color:#28A74B;">Файл загружается!</p>');
                },
                dataType: 'json',
                error: function () {
                    $('#uploadStatus').html('<p style="color:#EA4335;">File upload failed, please try again.</p>');
                },
                success: function (resp) {
                    if (resp.success) {
                        $('#uploadForm')[0].reset();
                        $('#uploadStatus').html('<p style="color:#28A74B;">Файл успешно загружен!</p>');

                        var image_data = resp.message;
                        let image_html = '';
                        for (let i = 0; i < image_data.length; i++) {
                            if (image_data[i].data.type == 'audio') {
                                image_html += `
                                    <div class="col mb-4" id="image_${image_data[i].data.id}">
                                      <div class="card py-0 h-100 overflow-hidden">
                                         <audio class="album-photo" controls="" src="${image_data[i].file_path}">
                                           Your browser does not support the audio element.
                                         </audio>
                                        <div class="card-body d-flex px-3 flex-column justify-content-between" style=" padding: 10px; ">
                                          <div class="small">
                                            <span class="text-nowrap pr-2">
                                            Добавлено: Я
                                            </span>
                                          </div>
                                        </div>
                                        <div class="card-footer d-flex justify-content-between" style=" padding-bottom: 0px; ">
                                          <div class="input-group mb-3">
                                            <input type="text" value="[audio]${image_data[i].data.name}[/audio]" id="photo${image_data[i].data.id}" class="form-control">
                                            <button onclick="copybbcode('photo${image_data[i].data.id}')" class="btn btn-primary">Copy</button>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                    `;
                            } else {
                                image_html += `
                                    <div class="col mb-4" id="image_${image_data[i].data.id}">
                                      <div class="card py-0 h-100 overflow-hidden">
                                        <div class="album-photo" style="background: url('${image_data[i].file_path}');"></div>
                                        <div class="card-body d-flex px-3 flex-column justify-content-between" style=" padding: 10px; ">
                                          <div class="small">
                                            <span class="text-nowrap pr-2">
                                            Добавлено: Я
                                            </span>
                                          </div>
                                        </div>
                                        <div class="card-footer d-flex justify-content-between" style=" padding-bottom: 0px; ">
                                          <div class="input-group mb-3">
                                            <input type="text" value="[img]${image_data[i].data.name}[/img]" id="photo${image_data[i].data.id}" class="form-control">
                                            <button onclick="copybbcode('photo${image_data[i].data.id}')" class="btn btn-primary">Copy</button>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                    `;
                            }
                        }
                        $('#boshi').prepend(image_html);
                    } else if (resp.error) {
                        if (resp.message) {
                            $('#uploadStatus').html('<p style="color:#EA4335;">' + resp.message + '</p>');
                        } else {
                            $('#uploadStatus').html('<p style="color:#EA4335;">File upload failed, please try again.</p>');
                        }
                    } else {
                        alert(resp.error.message);
                    }
                }
            });
        });

        // File type validation
        $("#fileInput").change(function () {
            var allowedTypes = ['image/jpeg', 'image/png', 'image/jpg', 'image/gif', 'audio/mp3', 'audio/ogg', 'audio/wav', 'audio/mpeg', 'video/mp4', 'video/webm'];
            var file = this.files[0];
            console.log(file.type);
            var fileType = file.type;
            if (!allowedTypes.includes(fileType)) {
                alert('Ошибка формата файла Разрешается: (JPEG/JPG/PNG/GIF/MP3/OGG).');
                $("#fileInput").val('');
                return false;
            }
        });
    });
</script>
